baseURL = 'https://jefforyamos.github.io/blog/'
languageCode = 'en-us'
title = 'Jeff Ward Rants and Raves'
theme = "ananke"

DefaultContentLanguage = "en"
SectionPagesMenu = "main"
Paginate = 6 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = ""
enableRobotsTXT = true

[languages]
  [languages.en]
    title = "Jeff Ward Rants and Raves"
    weight = 1
    contentDir = "content/en"
    # languageDirection = 'rtl' for Right-To-Left languages

  #[languages.fr]
  #  title = "Ananke Fr"
  #  weight = 2
  #  contentDir = "content/fr"

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  text_color = ""
  author = ""
  favicon = ""
  site_logo = ""
  description = "I may be hot, I may be cold, but lukewarm I'm not."
  # choose a background color from any on this page: https://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"
  recent_posts_number = 3

[[params.ananke_socials]]
# name = "twitter"
# url = "https://twitter.com/GoHugoIO"

  name = "facebook"
  url = "https://www.facebook.com/jeff.ward.14/"
